name: CI – NeoHealth

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  backend:
    name: Backend – install OK
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install backend dependencies
        working-directory: backend
        run: npm install --legacy-peer-deps

  frontend:
    name: Frontend – build OK
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install frontend dependencies
        working-directory: frontend
        run: npm install --legacy-peer-deps

      - name: Build frontend
        working-directory: frontend
        run: CI=false npm run build

  docker-build:
    name: Docker – build images
    runs-on: ubuntu-latest
    needs:
      - backend
      - frontend

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build backend image
        run: docker build -t backend-ci ./backend

      - name: Build frontend image
        run: docker build -t frontend-ci ./frontend

    docker-publish:
    name: Docker – push images to Docker Hub
    runs-on: ubuntu-latest
    needs: [docker-build]
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'

    env:
      DOCKERHUB_USER: ${{ secrets.DOCKER_USERNAME }}
      BACK_IMAGE: hopital-backend
      FRONT_IMAGE: hopital-frontend

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ env.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build backend image
        run: |
          docker build \
            -t $DOCKERHUB_USER/$BACK_IMAGE:latest \
            -t $DOCKERHUB_USER/$BACK_IMAGE:${{ github.sha }} \
            ./backend

      - name: Build frontend image
        run: |
          docker build \
            -t $DOCKERHUB_USER/$FRONT_IMAGE:latest \
            -t $DOCKERHUB_USER/$FRONT_IMAGE:${{ github.sha }} \
            ./frontend

      - name: Push backend image
        run: |
          docker push $DOCKERHUB_USER/$BACK_IMAGE:latest
          docker push $DOCKERHUB_USER/$BACK_IMAGE:${{ github.sha }}

      - name: Push frontend image
        run: |
          docker push $DOCKERHUB_USER/$FRONT_IMAGE:latest
          docker push $DOCKERHUB_USER/$FRONT_IMAGE:${{ github.sha }}
